version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: ms_usuarios_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: plazoleta_usuarios
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: juan
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Opcional: archivo de creación

volumes:
  postgres_data:
